fields = ['Modulbezeichnung:',
          'engluodulbezeichnung:',
          'ggf. Modulniveau:',
          'Kürzel:',
          'ggf. Untertitel:',
          'ggf. Lehrveranstaltungen:',
          'Studiensemester:',
          'Modulverantwortliche(r):',
          'Dozent(in):',
          'Sprache:',
          'Zuordnung zum Curriculum:',
          'Lehrform / SWS:',
          'Arbeitsaufwand:',
          'Kreditpunkte:',
          'Voraussetzungen nach Prüfungsordnung:',
          'Empfohlene Voraussetzungen:',
          'Angestrebte Lernergebnisse:',
          'Inhalt:',
          'Studien-/ Prüfungsleistungen:',
          'Medienformen:',
          'Literatur:']

fields_tn = [
    ['Modulbezeichnung:', 'course_name:'],
    ['engluodulbezeichnung:', 'course_name_en:'],
    ['ggf. Modulniveau:', 'if necessary module level:'],
    ['Kürzel:', 'short_code:'],
    ['ggf. Untertitel:', 'if necessary subtitles:'],
    ['ggf. Lehrveranstaltungen:', 'possibly courses:'],
    ['Studiensemester:', 'preferred_semester:'],
    ['Modulverantwortliche(r):', 'working_group:'],
    ['Dozent(in):', 'faculty:'],
    ['Sprache:', 'language:'],
    ['Zuordnung zum Curriculum:', 'module:'],
    ['Lehrform / SWS:', 'type_of_course:'],
    ['Arbeitsaufwand:', 'study_hours:'],
    ['Kreditpunkte:', 'credits:'],
    ['Voraussetzungen nach Prüfungsordnung:', 'requirements according to examination regulations:'],
    ['Empfohlene Voraussetzungen:', 'recommended requirements:'],
    ['Angestrebte Lernergebnisse:', 'learning outcomes:'],
    ['Inhalt:', 'content:'],
    ['Studien-/ Prüfungsleistungen:', 'study / Examinations:'],
    ['Medienformen:', 'teaching style:'],
    ['Literatur:', 'literature:']
    ]
